FROM alpine:3.18.2

RUN apk update && \
    apk add --no-cache cmake make g++ gtest-dev gmock 

WORKDIR /app

COPY . /app

RUN cmake -B build && cd build && make 

ENTRYPOINT [ "/app/build/tests/DifferentialEquationsSolverTests" ]

#TODO: fix compiler and gtest versions
