FROM alpine:3.18.2

RUN apk update && \
    apk add --no-cache cmake make g++ gtest-dev gmock 

WORKDIR /app

COPY src/ ./src/
COPY tests/ ./tests/
COPY CMakeLists.txt .

RUN cd tests && cmake -B build && cd build && cmake .. && make
# && make test #TODO: figure out how to run tests using "make test"

ENTRYPOINT [ "/app/tests/build/DifferentialEquationsSolverTests" ]

#TODO: check smaller base images
#TODO: fix compiler and gtest versions
