FROM alpine:3.18.2

RUN apk update && \
    apk add --no-cache cmake make g++ gtest-dev gmock 

WORKDIR /app

COPY src/ ./src/
COPY tests/ ./tests/
COPY CMakeLists.txt .

RUN cmake -B build && cd build && make 

ENTRYPOINT [ "/app/build/src/DifferentialEquationsSolver" ]

#TODO: check smaller base images
#TODO: fix compiler and gtest versions
