name: Release job

on:
  push:
      branches: 'master'

jobs:
  build-and-test-and-publish-to-dockerhub:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev libgmock-dev
      - name: build tests
        run: |
          cmake -B build
          cd build
          make
      - name: run tests
        run: ./build/tests/DifferentialEquationsSolverTests  
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/diff-eq-solver:${{github.run_number}}, ${{ secrets.DOCKERHUB_USERNAME }}/diff-eq-solver:latest
